#ifndef THIRD_PARTY_MODBUS_LIB_CONFIG_MODBUSCONFIG_H_
#define THIRD_PARTY_MODBUS_LIB_CONFIG_MODBUSCONFIG_H_

#define ENABLE_TCP 1
#define ENABLE_USB_CDC 0
#define ENABLE_USART_DMA 0

#define T35 5
#define MAX_BUFFER 260
#define TIMEOUT_MODBUS 300
#define MAX_M_HANDLERS 2
#define MAX_TELEGRAMS 8

#if ENABLE_TCP == 1
#define NUMBERTCPCONN 1
#define TCPAGINGCYCLES 400
#define TCP_SERVER_RECV_TIMEOUT_MS 6000U
#define TCP_SERVER_IDLE_TIMEOUT_MS 60000U
#endif

#endif /* THIRD_PARTY_MODBUS_LIB_CONFIG_MODBUSCONFIG_H_ */
